name: Android APK Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Force Gradle Build
        run: ./gradlew clean assembleDebug --stacktrace --info

      - name: List output files (Debugging)
        run: ls -R app/build/outputs/apk || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: app/build/outputs/apk/**/*.apk
